# @package _global_

defaults:
  - _self_
  - data: dummy # choose datamodule with `test_dataloader()` for evaluation
  - energy: gmm
  - model: dem
  - launcher: null
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  - experiment: gmm

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
