_target_: dem.energies.gmm_energy.GMM

dimensionality: 2
n_mixes: 4
loc_scaling: 4
log_var_scaling: 0.3

device: ${trainer.accelerator}

plot_samples_epoch_period: 1

#add this only for eval
#data_path_train: "/scratch/bq216/code/DEM/dem_results/logs/train/runs/2024-07-04_16-14-11/samples_100000.pt"
#data_path_val: ${energy.data_path_train}
#for train
data_path_train: null
data_path_val: null

should_unnormalize: 
data_normalization_factor: 16
