_target_: dem.energies.gmm_energy.GMM

dimensionality: 10
n_mixes: 40
loc_scaling: 40
log_var_scaling: 1.0

device: ${trainer.accelerator}

plot_samples_epoch_period: 1

should_unnormalize: true
data_normalization_factor: 50

#data_path_train: "/home/bq216/codes/beidem/dem_results/logs/train/runs/2024-09-03_12-30-15/samples_100000.pt"
#data_path_val: ${energy.data_path_train}
