_target_: dem.energies.many_well_energy.ManyWellEnergy

dimensionality: 32

plot_samples_epoch_period: 1
data_normalization_factor: 1.0
device: ${trainer.accelerator}

#data_path_train: "<YOURPATH>/samples_100000.pt"
#data_path_val: ${energy.data_path_train}
