_target_: dem.models.components.mlp.MyFourierMLP
_partial_: true
hidden_size: 128
hidden_layers: 3
emb_size: 128
time_emb: "sinusoidal"
input_emb: "learnable"
input_dim: ${energy.dimensionality}
out_dim: ${energy.dimensionality}
